config/routes.rb
Quote::Application.routes.draw do
	resources :notes do  
	collection do
	 get 'result' 
	 end 
	 collection do
	 get 'rss' 
	 end 
	
  resources :comments
  resources :likes
end

  resources :posts

  get "home/index"

   

  resource :account, :controller => "users"
  resources :users

end

 ActionController::Routing::Routes.draw do |map|
  map.resource :account, :controller => "users"
  map.resources :users
  map.resource :user_session
  map.root :controller => "user_sessions", :action => "new"
end

app/models/note.rb
class Note < ActiveRecord::Base
validates :title,  :presence => true
validates :content, :presence => true
validates :author,  :presence => true
validates :genre, :presence => true
validates_numericality_of :year, :greater_than => 1, :less_than => 2015

has_many :comments
acts_as_taggable
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.xml
  def index
    @notes = Note.all

    respond_to do |format|
	    print format
      format.html # index.html.erb
      format.xml  { render :xml => @notes }
	  
    end
  end

  # GET /notes/result
  # GET /notes/result.xml
  def result
	  print "\n\nstart:"
	  print params[:tags]
	  print ":end \n\n"
	  print Note.tagged_with(params[:tags])

    @notes = Note.tagged_with(params[:tags])

   
    respond_to do |format|
      format.html # result.html.erb
      format.xml  { render :xml => nil }
    end
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @note = Note.find(params[:id])
    @newyear = params[:year]
   # if @isclicked != 1
	@note.year  +=1
   # else 
	#@note.year = 2
#end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.xml
  def create
    @note = Note.new(params[:note])
	@note.tag_list = @note.tag_list.push(@note.author)
	@note.tag_list = @note.tag_list.push(@note.genre)
    respond_to do |format|
      if @note.save
	    print '\n\nBelow is the taglist'
		print @note.tag_list
        format.html { redirect_to(@note, :notice => 'Note was successfully created.') }
        format.xml  { render :xml => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to(@note, :notice => 'Note was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to(notes_url) }
      format.xml  { head :ok }
    end
  end
  
  def increment 
  @note = Note.find(params[:id])
  @note.year  += 1
  
      respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @note }
    end

  end
  
  def rss
	@notes = Note.find :all, :limit => 5, :order => 'created_at DESC'

    respond_to do |format|
	    print format
 #response.headers['Content-Type'] = 'application/rss+xml'
 # Render the feed using an RXML template
 #render :file => 'rss.html.erb'
	format.html
	  format.rss { render :action => "feed.rxml", :layout => false }
    end
  end
  
  
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <%= f.hidden_field :owner, :value => current_user.login %>
  
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div>
	<%= f.label :tag_list %><br/>
	<%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/increment.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>Content:</b>
  <%= @note.content %>
</p>

<p>
  <b>Year:</b>
  <%= @note.year %>
</p>

<p>
  <b>Author:</b>
  <%= @note.author %>
</p>

<p>
  <b>Genre:</b>
  <%= @note.genre %>
</p>

<p>
  <b>Tags:</b>
  <%= @note.tags %>
</p>

 
  <%= @note.year %>
  
  <input type = "button" name = "like" value = "like"   onclick="<%= remote_function(:update => "notes",
:url => { :action => :show }, :with => "id={@note}") %>">
  


 <%= @note.year %>

<h2>Comments</h2>
<% @note.comments.each do |comment| %>
  <p>
    <b>Commenter:</b>
    <%= comment.commenter %>
  </p>

  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@note, @note.comments.build]) do |f| %>
  

  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>Owner</th>
    <th>Title</th>
	<th>Content</th>
    <th>Year</th>
    <th>Author</th>
    <th>Genre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.owner %></td>
    <td><%= note.title %></td>
    <td><%= note.content %></td>
    <td><%= note.year %></td>
    <td><%= note.author %></td>
    <td><%= note.genre %></td>

    <td><%= link_to 'Show', note %></td>
	<% if current_user.login == note.owner %>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
	<td><%= link_to 'Destroy', note, :confirm => 'Are you sure?', :method => :delete %></td>
	<% end %>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<%= link_to 'RSS Feed', :controller => "notes", :action => "rss" %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/result.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>Owner</th>
    <th>Title</th>
    <th>Content</th>
    <th>Year</th>
    <th>Author</th>
    <th>Genre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.owner %></td>
    <td><%= note.title %></td>
    <td><%= note.content %></td>
    <td><%= note.year %></td>
    <td><%= note.author %></td>
    <td><%= note.genre %></td>

    <td><%= link_to 'Show', note %></td>
	<% if current_user.login == note.owner %>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
	<td><%= link_to 'Destroy', note, :confirm => 'Are you sure?', :method => :delete %></td>
	<% end %>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/rss.rss.erb
xml.instruct! :xml, :version => "1.0"
xml.rss :version => "2.0" do
  xml.channel do
    xml.title "Your Blog Title"
    xml.description "A blog about software and chocolate"
    xml.link notes_url

    for note in @notes
      xml.item do
        xml.title note.title
        xml.description note.content
        xml.pubDate note.created_at.to_s(:rfc822)
        xml.link note_url(note)
        xml.guid note_url(note)
      end
    end
  end
end

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>Content:</b>
  <%= @note.content %>
</p>

<p>
  <b>Year:</b>
  <%= @note.year %>
</p>

<p>
  <b>Author:</b>
  <%= @note.author %>
</p>

<p>
  <b>Genre:</b>
  <%= @note.genre %>
</p>

<p><b> Tag List </b> 

<% @note.tag_list.each do |tag| %>
<%= link_to tag, :controller => "notes", :action => "result", :tags => tag %> 
<%end%>
</p>


<h3>Comments</h3>
<% @note.comments.each do |comment| %>
  <p>
    <b>Commenter:</b>
    <%= comment.commenter %>
  </p>

  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>
<% end %>

<b>Add a comment:</b>
<%= form_for([@note, @note.comments.build]) do |f| %>
  

  <div class="field">
    <%= f.label :commenter %>: <%=h current_user.login %> <br/>
	<%= f.hidden_field :commenter, :value => current_user.login %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>