config/routes.rb
Quote::Application.routes.draw do
	resources :notes do  
	collection do
	 get 'result' 
	 end 
	 collection do
	 get 'rss' 
	 end 
	
  resources :comments
  resources :likes
end

  resources :posts

  get "home/index"

   

  resource :account, :controller => "users"
  resources :users

end

 ActionController::Routing::Routes.draw do |map|
  map.resource :account, :controller => "users"
  map.resources :users
  map.resource :user_session
  map.root :controller => "user_sessions", :action => "new"
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
	if @user.save
      flash[:notice] = "Account registered!"
      redirect_back_or_default notes_path
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.erb
<%= form.label :login %><br />
<%= form.text_field :login %><br />
<br />
<%= form.label :password, form.object.new_record? ? nil : "Change password" %><br />
<%= form.password_field :password %><br />
<br />
<%= form.label :password_confirmation %><br />
<%= form.password_field :password_confirmation %><br />

app/views/users/edit.html.erb
<h1>Edit My Account</h1>

<% form_for @user, :url => account_path do |f| %>
  
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update" %>
<% end %>

<br />

<!-- <%= link_to "My Profile", account_path %> -->

app/views/users/new.html.erb
<h1>Register</h1>

<% form_for @user, :url => account_path do |f| %>
  <!--%= f.error_messages %-->
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<p>
  <b>Login:</b>
  <%=h @user.login %>
</p>

<p>
  <b>Login count:</b>
  <%=h @user.login_count %>
</p>

<p>
  <b>Last request at:</b>
  <%=h @user.last_request_at %>
</p>

<p>
  <b>Last login at:</b>
  <%=h @user.last_login_at %>
</p>

<p>
  <b>Current login at:</b>
  <%=h @user.current_login_at %>
</p>

<p>
  <b>Last login ip:</b>
  <%=h @user.last_login_ip %>
</p>

<p>
  <b>Current login ip:</b>
  <%=h @user.current_login_ip %>
</p>


<%= link_to 'Edit', edit_account_path %>

<%= link_to 'Proceed to Main Page', notes_path %>